language: python
python: "3.6"
services:
  - postgresql
install:
  - pip install tox
  - pip install -r requirements-test.txt
before_script:
  - psql -c 'create database "django-amber-test";' -U postgres
script: tox -e py36
